ci

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,7 +28,21 @@ jobs:
       run: python -m django --version
 
     - name: test
+      id: run_tests
       run: python manage.py test
+      continue-on-error: true
+
+    - name: Check test results
+      if: steps.run_tests.outcome == 'success'
+      run: echo "bien joué"
+
+    - name: Handle test failures
+      if: steps.run_tests.outcome != 'success'
+      run: echo "test failed" && exit 1
+
+    - name: check coverage
+      run: coverage run --source='.' manage.py test; coverage report
+
   lint:
     runs-on: ubuntu-latest
 
